// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tldfveoukmewmvhmwkzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsZGZ2ZW91a21ld212aG13a3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTUwNTMsImV4cCI6MjA1OTQzMTA1M30.LVe40vuL3OsgGH6i8RqT6HI49h6nr4BMxtboQ-cFU2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);